### ISSUE TITLE
Init tool help attribute

### ISSUE THREAD

**Issue by bernt-matthias** [erasche/galaxyxml#36]
Maybe to `""` or `"TODO"`? 

Otherwise

```
Traceback (most recent call last):
  File "/home/berntm/projects/mb-galaxy-tools/tools/saqc/gen.py", line 59, in <module>
    print(tool.export())
  File "/home/berntm/projects/mb-galaxy-tools/tools/saqc/.venv/lib/python3.10/site-packages/galaxyxml/tool/__init__.py", line 201, in export
    help_element.text = etree.CDATA(export_xml.help)
AttributeError: 'Tool' object has no attribute 'help'
```

**Comment by hexylena** [comment]
makes sense to me. TODO sounds good
